# Generated by Django 2.2.3 on 2019-07-17 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('canal', models.CharField(choices=[('email', 'email'), ('celular', 'celular'), ('fixo', 'fixo')], max_length=10)),
                ('valor', models.CharField(max_length=100)),
                ('obs', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
